name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Test std
        run: cargo test

      - name: Test no-std
        run: cargo test --no-default-features

      # Check that benchmarks compile without running them
      - name: Check bench
        run: cargo check --bench benches
